### ISSUE TITLE
Django 2.0 compatibility

### ISSUE THREAD

**Issue by godlike64** [jbittel/django-mama-cas#58]
I am trying to set up a mock with django-mama-cas + django-cas-ng under Python 3.6 and Django 2.0. Unfortunately, it appears django-mama-cas is not compatible with Django 2.0. Trying to run manage.py migrate yields:

```
$ ./manage.py migrate
Traceback (most recent call last):
  File "./manage.py", line 15, in <module>
    execute_from_command_line(sys.argv)
  File "/home/godlike/virtualenv/36/lib/python3.6/site-packages/django/core/management/__init__.py", line 371, in execute_from_command_line
    utility.execute()
  File "/home/godlike/virtualenv/36/lib/python3.6/site-packages/django/core/management/__init__.py", line 347, in execute
    django.setup()
  File "/home/godlike/virtualenv/36/lib/python3.6/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/godlike/virtualenv/36/lib/python3.6/site-packages/django/apps/registry.py", line 112, in populate
    app_config.import_models()
  File "/home/godlike/virtualenv/36/lib/python3.6/site-packages/django/apps/config.py", line 198, in import_models
    self.models_module = import_module(models_module_name)
  File "/home/godlike/virtualenv/36/lib64/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/godlike/virtualenv/36/lib/python3.6/site-packages/mama_cas/models.py", line 32, in <module>
    from mama_cas.utils import add_query_params
  File "/home/godlike/virtualenv/36/lib/python3.6/site-packages/mama_cas/utils.py", line 5, in <module>
    from django.core import urlresolvers
ImportError: cannot import name 'urlresolvers'
```

**Comment by manelclos** [comment]
Hi @godlike64, there is a PR for Django 2.0 compatibility, you may want to try that branch and tell us how it works: https://github.com/jbittel/django-mama-cas/pull/56

**Comment by godlike64** [comment]
Yeah, I saw that PR only **after** I had manually patched the code to work with Django 2.0. It's basically the same I did (sans for the testing part). I have it working under Django 2.0. Any ideas when this will get merged @manelclos ?

**Comment by manelclos** [comment]
I'm not a maintainer, we will need to wait for review. I'm also looking forward to have it merged because I'm using it in production along Django 2.0 and I prefer not to use forks if possible.

**Comment by manelclos** [comment]
@godlike64 PR https://github.com/jbittel/django-mama-cas/pull/56 has been merged today, mama-cas is now Django 2.0 ready!

**Comment by FredeJ** [comment]
Any overview of when this will be released to pypi? :)
